### ISSUE TITLE
list-style-type not appearing for bullets or ordered lists in Wordpress Admin Editor

### ISSUE THREAD

**Issue by sigmacitizen** [eddiemachado-zz/bones#767]
Issue is exact as title. I've tried a few installs so I don't think it's specific to me. Is there something I'm missing or do they just not work?

**Comment by semelina** [comment]
Hi. I had the same issue and just fixed it. Maybe someone has the same problem and this helps: for me it was a wrong sass compiler setup. My changes were put in the wrong directory.
I use the brackets editor with the "Brackets SASS" plugin. In the plugini’s config file (.brackets.jason) the right output was only set for the style.scss file. I changed the path from "library/scss/style.scss" to "library/scss/*.scss" and now it works and all the sass files are compiled correctly.

**Comment by kstarcher** [comment]
The editor seems to be taking on the list styles from the front-facing theme. You can fix it by adding this into editor-style.scss:

			ul {
				list-style-type: disc !important;
				padding-left: 2em;
				li {}

			}

			ol {
				list-style-type: decimal !important;
				padding-left: 2em;
				li {}

			}

**Comment by cosmocanuck** [comment]
For the life of me I can not get this to work. I'm adding the suggested css into my editor-style.scss but no go. 

I see in the Inspector that this is being applied to my editor's UL:

```
/* line 279, ../scss/partials/_normalize.scss */
body#tinymce.wp-editor nav ul,
body#tinymce.wp-editor nav ol {
  list-style: none;
  list-style-image: none;
}
```

Which doesn't match what I've added at that point in my normalize.scss file.

I'm using Compass... any ideas?

**Comment by Hlsgs** [comment]
Comment out this line in `functions.php`:
```
add_editor_style( get_stylesheet_directory_uri() . '/library/css/editor-style.css' );
```

**Comment by cosmocanuck** [comment]
THANK YOU! After much futzing around with trying to re-enable bulleted lists and such… this was the perfect fix. I don’t need to change the editor style sheet. And I’d never have found this myself!
